version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: hari
      POSTGRES_PASSWORD: ExpressTodoApp
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hari -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: